git checkout --ours --     org.eclipse.egit-feature/feature.xml
git checkout --ours --     org.eclipse.egit-feature/pom.xml
git checkout --ours --     org.eclipse.egit.core.test/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.core.test/pom.xml
git checkout --ours --     org.eclipse.egit.core/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.core/pom.xml
git checkout --ours --     org.eclipse.egit.doc/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.doc/pom.xml
git checkout --ours --     org.eclipse.egit.import-feature/feature.xml
git checkout --ours --     org.eclipse.egit.import-feature/pom.xml
git checkout --ours --     org.eclipse.egit.import/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.import/pom.xml
git checkout --ours --     org.eclipse.egit.mylyn-feature/feature.xml
git checkout --ours --     org.eclipse.egit.mylyn-feature/pom.xml
git checkout --ours --     org.eclipse.egit.mylyn.ui.test/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.mylyn.ui.test/pom.xml
git checkout --ours --     org.eclipse.egit.mylyn.ui/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.mylyn.ui/pom.xml
git checkout --ours --     org.eclipse.egit.repository/pom.xml
git checkout --ours --     org.eclipse.egit.source-feature/feature.xml
git checkout --ours --     org.eclipse.egit.source-feature/pom.xml
git checkout --ours --     org.eclipse.egit.target/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.target/pom.xml
git checkout --ours --     org.eclipse.egit.ui.test/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.ui.test/pom.xml
git checkout --ours --     org.eclipse.egit.ui/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit.ui/pom.xml
git checkout --ours --     org.eclipse.egit/META-INF/MANIFEST.MF
git checkout --ours --     org.eclipse.egit/pom.xml
git checkout --ours --     pom.xml